"""The input-id / output-class contract: 4-gram in, next byte out.

This test module exists because the two halves of the public surface disagreed
about what one "token" is, and nothing failed when they did.

The model is unambiguous once you read it: ``HashBind`` embeds one *byte
4-gram* per position, and the unembedding is ``(d_model, output_vocab)`` with
``output_vocab == 256``. So one input id is a packed 4-gram and one output class
is a single byte. The frozen task is next-byte prediction from a 4-gram
context.

``encode_bytes`` implements the input side, and the generation loop consumes
its ids. :func:`bhanox.generate.generate` used to sample from the 256-way head
and feed that byte back as if it were a 4-gram id, so after the first generated
byte the model conditioned on a different context than the text it appeared to
be continuing. The API decision taken in the M2 report: the high-level entry
point is byte-oriented and hides ids, and the low-level entry point takes ids
and returns *only* generated byte values, so prompt ids and byte values never
share a return array.

What is pinned here is the 4-gram encoding, the target byte, the rolling window,
and the fact that the loop actually rolls rather than feeding bare bytes.
"""

from __future__ import annotations

import numpy as np
import pytest

from bhanox.config import load_config
from bhanox.frontend.hashbind import BYTE_GRAM_ORDER, encode_bytes
from bhanox.generate import generate, generate_ids
from bhanox.model import Bhanox

#: 4-gram order is frozen big-endian, so "abcd" and "bcde" differ in the high
#: bits as well as the low ones. If this ever changes, every trained embedding
#: row becomes meaningless, so it is worth a test of its own.
GRAM = 4

PROMPT_BYTES = b"hello world"


def targets_for(raw: bytes) -> np.ndarray:
    """The next byte after each 4-gram in ``raw``.

    Local to this module on purpose. The trainer (M2) needs this as public API,
    but adding it here would be Section 6 work, and the exact shape it should
    take depends on the windowing decision recorded in the report.
    """
    return np.frombuffer(raw, dtype=np.uint8)[GRAM:].astype(np.int64)


def roll(prev_gram_id: int, next_byte: int) -> int:
    """The next model input: shift the window left, append the sampled byte.

    This is the only coherent next input. A 4-gram id is the packed window, so
    advancing one byte is ``prev[1:] + [next_byte]`` and nothing else.
    """
    window = int(prev_gram_id).to_bytes(GRAM, "big")[1:] + bytes([next_byte])
    return int(encode_bytes(window, n=GRAM)[0])


def ungram(gram_id: int) -> bytes:
    """Inverse of :func:`encode_bytes` for a single id."""
    return int(gram_id).to_bytes(GRAM, "big")


@pytest.fixture(scope="module")
def model() -> Bhanox:
    return Bhanox(load_config("nano"))


class TestOneIdIsOneGram:
    def test_a_gram_is_the_packed_window_big_endian(self) -> None:
        assert BYTE_GRAM_ORDER == "big"
        assert int(encode_bytes(b"abcd")[0]) == 0x61626364

    def test_the_order_is_not_palindromic(self) -> None:
        """Big-endian is load-bearing: reversed packing gives the same set of
        ids for a reversed string, so a mirrored corpus would train on garbage
        that still hashes to valid rows."""
        assert int(encode_bytes(b"abcd")[0]) != int(encode_bytes(b"dcba")[0])

    def test_the_window_slides_by_one_byte(self) -> None:
        assert encode_bytes(b"abcde").tolist() == [0x61626364, 0x62636465]

    def test_a_short_input_yields_no_grams(self) -> None:
        assert encode_bytes(b"abc").tolist() == []

    def test_a_gram_id_needs_32_bits(self) -> None:
        """A 4-gram is 4 bytes. If ids were byte values they could not exceed
        255, and every real corpus id would land inside the direct table."""
        assert int(encode_bytes(b"\xff\xff\xff\xff")[0]) == 2**32 - 1


class TestTheTargetIsTheNextByte:
    def test_the_byte_after_a_known_gram(self) -> None:
        assert targets_for(b"abcde").tolist() == [ord("e")]
        # "hell" predicts 'o'; "ello" predicts nothing, being the dropped last
        # gram. Checked per-gram so a windowing slip cannot hide behind a count.
        assert [ungram(g) for g in encode_bytes(b"hello")] == [b"hell", b"ello"]
        assert targets_for(b"hello").tolist() == [ord("o")]

    def test_every_gram_is_a_shifted_window(self) -> None:
        raw = b"hello world"
        assert [ungram(g) for g in encode_bytes(raw)] == [
            raw[i : i + GRAM] for i in range(len(raw) - GRAM + 1)
        ]

    def test_the_last_gram_has_no_target_and_is_dropped(self) -> None:
        """A gram at position i predicts the byte at i + n, so a buffer of L
        bytes gives L - n + 1 inputs but only L - n targets.

        This off-by-one is the part of the contract most likely to be fumbled
        when the trainer cuts its windows, and it is why the last gram of a
        buffer cannot be used as an input.
        """
        raw = b"abcde"
        assert len(encode_bytes(raw)) == 2
        assert len(targets_for(raw)) == 1
        assert len(targets_for(raw)) == len(encode_bytes(raw)) - 1

    def test_the_targets_are_the_shift_by_four(self) -> None:
        raw = b"the quick brown fox"
        grams = encode_bytes(raw)
        targets = targets_for(raw)
        for i in range(len(grams) - 1):
            # Gram i covers bytes i..i+3, so its target is byte i+4 -- which is
            # the *last* byte of gram i+1's window (bytes i+1..i+4).
            assert ungram(grams[i + 1])[-1] == int(targets[i])
        assert targets.tolist() == list(raw[GRAM:])

    def test_every_target_is_a_byte_value(self) -> None:
        """The class space is 8 bits wide. This is the half of the contract that
        makes the rolling window necessary: an output class is not an input id."""
        t = targets_for(PROMPT_BYTES)
        assert t.min() >= 0 and t.max() < 256

    def test_the_two_id_spaces_are_not_interchangeable(self) -> None:
        """A byte value is a valid int64 and therefore a valid input id, which
        is exactly why mixing them cannot be caught by a type check."""
        assert ord("e") == 0x65
        assert roll(0x61626364, ord("e")) == 0x62636465
        assert roll(0x61626364, ord("e")) != ord("e")


class TestTheRollingWindow:
    def test_the_window_shifts_left_and_appends(self) -> None:
        assert roll(0x61626364, ord("e")) == 0x62636465

    def test_the_window_keeps_the_last_three_bytes(self) -> None:
        assert roll(0x61626364, 0xFF) == 0x626364FF

    def test_chained_windows_track_the_text(self) -> None:
        raw = PROMPT_BYTES
        ids = encode_bytes(raw)
        window = int(ids[0])
        for offset, nxt in enumerate(raw[GRAM:]):
            window = roll(window, nxt)
            # After the k-th roll the window must be the k+1-th 4-gram.
            assert window == int(ids[offset + 1])

    def test_the_direct_byte_feed_is_a_different_context(self) -> None:
        """The measured failure. The byte 167 fed straight back is the 4-gram
        0x000000A7; the coherent next input is 0x7F0000A7. Both are valid int64
        ids, so the model accepts both and the caller cannot tell them apart.
        """
        prev = int(encode_bytes(b"\xfb\x7f\x00\x00")[0])
        assert prev == 0xFB7F0000
        assert roll(prev, 167) == 0x7F0000A7
        assert 167 == 0x000000A7
        assert roll(prev, 167) != 167

    def test_nano_shapes_agree_with_the_contract(self, model: Bhanox) -> None:
        cfg = load_config("nano")
        assert cfg.output_vocab == 256, "one output class per byte value"
        ids = encode_bytes(PROMPT_BYTES)
        # One embedding per position: (B, T) 4-grams in, (B, T, 256) out.
        assert model.embed(ids[None, :]).shape == (1, len(ids), cfg.d_model)
        assert model.forward(ids[None, :]).shape == (1, len(ids), cfg.output_vocab)


class _Recording:
    """A model whose ``step`` records its inputs and returns fixed logits.

    The defect this module documents was invisible from the outside: a bare
    ``int64`` byte and a packed 4-gram are the same type, and the returned
    array looked fine either way. So the loop is checked by watching what the
    model is *fed*, not what it returns.
    """

    def __init__(self, model: Bhanox, byte: int) -> None:
        self.model = model
        self.seen: list[int] = []
        self.byte = byte

    def step(self, ids: object) -> np.ndarray:
        self.seen.append(int(np.asarray(ids).reshape(-1)[0]))
        logits = np.zeros(int(self.model.config.output_vocab), dtype=np.float32)
        logits[self.byte] = 1.0
        return logits

    def reset(self) -> None:
        self.seen.clear()


def recording(cfg: object, byte: int) -> _Recording:
    """A real model with its ``step`` and ``reset`` swapped for the recorder."""
    rec = _Recording(Bhanox(cfg), byte)  # type: ignore[arg-type]
    rec.model.step = rec.step  # type: ignore[method-assign]
    rec.model.reset = rec.reset  # type: ignore[method-assign]
    return rec


class TestGenerateFollowsTheRollingWindow:
    """The defect, now pinned as fixed.

    ``strict=True`` used to sit on the "should" test below, so fixing
    :func:`bhanox.generate` without updating this module turned into a suite
    failure rather than a silent behaviour change. It is now an ordinary test
    for the same reason: the loop must roll, and if it stops rolling the byte
    feed comes back, this goes red.
    """

    def test_the_model_is_fed_the_windows_of_the_text_it_returns(self) -> None:
        """One invariant, stated so it covers every length and every byte.

        The ids the model consumed are exactly the 4-gram windows of the
        returned text -- the prompt's, then one per generated byte. The old loop
        fed the bare sampled byte instead, which is a valid ``int64`` and so
        could not be caught by a type check.
        """
        rec = recording(load_config("nano"), byte=ord("X"))
        out = generate(rec.model, b"abcde", max_new=3, temperature=0.0)
        assert out == b"abcdeXXX"
        assert rec.seen == encode_bytes(out, n=GRAM).tolist()

    def test_the_fed_window_shifts_left_by_one_byte_each_step(self) -> None:
        rec = recording(load_config("nano"), byte=0xFF)
        generate(rec.model, b"\xfb\x7f\x00\x00", max_new=2, temperature=0.0)
        # The measured failure, restated as what now happens. The first fed id is
        # the prompt window 0xFB7F0000; the next is 0x7F0000FF, which is
        # 0x000000FF's predecessor in the right direction -- three bytes of
        # history shifted in, where the old loop sent the bare 0x000000FF.
        assert rec.seen == [0xFB7F0000, 0x7F0000FF, 0x0000FFFF]
        assert 0x000000FF not in rec.seen

    def test_no_fed_id_after_the_prompt_is_a_bare_byte(self) -> None:
        """The distinction the defect turned on, asserted over a real run.

        A bare sampled byte is what the old loop fed. The rolled window is a
        different number, and it is the one that keeps three bytes of history.
        """
        byte = ord("q")
        rec = recording(load_config("nano"), byte=byte)
        out = generate(rec.model, PROMPT_BYTES, max_new=6, temperature=0.0)
        fed = rec.seen[len(PROMPT_BYTES) - GRAM + 1 :]
        assert fed, "the run generated something"
        for value in fed:
            assert value != byte, f"fed the bare byte {byte} instead of a window"
        # And each one really is the window the returned text implies.
        assert rec.seen == encode_bytes(out, n=GRAM).tolist()

    def test_a_longer_prompt_consumes_exactly_its_overlapping_windows(
        self,
    ) -> None:
        rec = recording(load_config("nano"), byte=ord("Z"))
        raw = b"the quick brown fox"
        generate(rec.model, raw, max_new=2, temperature=0.0)
        prompt_windows = [ungram(g) for g in encode_bytes(raw)]
        assert prompt_windows == [raw[i : i + GRAM] for i in range(len(raw) - GRAM + 1)]
        assert rec.seen[: len(prompt_windows)] == encode_bytes(raw).tolist()

    def test_the_low_level_api_rolls_the_same_way(self) -> None:
        rec = recording(load_config("nano"), byte=ord("X"))
        out = generate_ids(
            rec.model, encode_bytes(b"abcde"), max_new=3, temperature=0.0
        )
        assert rec.seen == encode_bytes(b"abcde" + bytes(out), n=GRAM).tolist()

    def test_the_low_level_api_returns_bytes_and_not_prompt_ids(
        self, model: Bhanox
    ) -> None:
        """The other half of the old defect: one array holding two id spaces.

        Prompt ids are 32-bit and generated values are 8-bit. The caller still
        holds the prompt, so nothing needs concatenating, and the return dtype
        says which space it is in.
        """
        prompt = encode_bytes(PROMPT_BYTES)
        out = generate_ids(model, prompt, max_new=8, temperature=0.0, seed=0)
        assert out.dtype == np.uint8, "byte values, not input-space ids"
        assert out.shape == (8,), "generated bytes only; the prompt is not echoed"
        assert out.max() < 256

    def test_the_byte_api_returns_bytes(self, model: Bhanox) -> None:
        out = generate(model, PROMPT_BYTES, max_new=8, temperature=0.0, seed=0)
        assert isinstance(out, bytes)
        assert len(out) == len(PROMPT_BYTES) + 8
        assert out[: len(PROMPT_BYTES)] == PROMPT_BYTES
